version: "3.9"
services:
  client:
    image: nginx
    volumes:
      - ./client/build:/usr/share/nginx/html
    ports:
      - "80:80"
  server:
    build: ./server
    volumes:
      - ./server:/workarea
      - ./database:/database
    ports:
      - "0.0.0.0:6789:6789"
